<div class="menu">
    <ul>
        <li><a href='<?php echo $this->url(array(
            "controller" => "stories",
            "action" => "view",
        ),null,true); ?>'>Stories</a></li>
        <li><a href='<?php echo $this->url(array(
            "controller" => "users",
            "action" => "view",
        ),null,true) ?>'>Profilo utente</a></li>
        <li><a href='<?php echo $this->url(array(
            "controller" => "bookmarks",
            "action" => "view",
        ),null,true) ?>'>Bookmars</a></li>
        <li><a href='<?php echo $this->url(array(
            "controller" => "users",
            "action" => "logout",
        ),null,true) ?>'>Logout</a></li>
    </ul>
</div>