<?php if( count($this->navigation) ): ?>
  <div class='menu'>
    <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
  </div>
<?php endif; ?>
<?php if( count($this->submenu) ): ?>
  <div class='menu sub' id="subMenu" style="background-color:<?php echo $this->user_preferred_color ?>">
    <?php echo $this->navigation()->menu()->setContainer($this->submenu)->render() ?>
  </div>
<?php endif; ?>
<div id="userContainer">
<div class="userProfileMenu">
<?php echo $this->render("profile/sidebar.phtml") ?>
</div>
    <div class="userProfileContainer">
        <div class="following">
        <?php if (count($this->whoIAmFollowing)) { ?>
            <h3><?php echo $this->translate('Following') ?>:</h3>
            <?php foreach ($this->whoIAmFollowing as $following) { ?>
                <?php $tmp = $following->getFollowedInfo(); ?>
                <a href='<?php echo $this->url(array(
                    "module" => "users",
                    "controller" => "profile",
                    "action" => "view",
                    "id" => $tmp->user_id,
                    ),null,true); ?>'><?php echo $tmp->user_name ?></a>
<?php if (Engine_Api_Users::getUserInfo()->user_id == $this->userDetails->user_id) : ?>
            - <a href='#' target='_blank' onclick="Engine_Api_SmootBox.open('<?php echo $this->url(array(
                        "module" => "users",
                        "controller" => "followers",
                        "action" => "del",
                        "idwriter" => $tmp->user_id,
                    ),null,true); ?>');return false;">Unfollow</a>
<?php endif; ?><br/>
            <?php } ?>
        <?php } else { ?>
            <h3>Empty list.</h3>
        <?php } ?>
        </div>
    </div>
</div>