<?php if( count($this->navigation) ): ?>
  <div class='menu'>
    <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
  </div>
<?php endif; ?>
<?php if( count($this->submenu) ): ?>
  <div class='menu sub' id="subMenu" style="background-color:<?php echo $this->user_preferred_color ?>">
    <?php echo $this->navigation()->menu()->setContainer($this->submenu)->render() ?>
  </div>
<?php endif; ?>
<div id="userContainer">
<div class="userProfileMenu">
<?php echo $this->render("profile/sidebar.phtml") ?>
</div>
    <div class="userProfileContainer">
        <div class="followers">
        <?php if (count($this->friends)) : ?>
            <h3><?php echo $this->translate('Friends') ?> (<?php echo count($this->friends) ?>)</h3>
            <?php foreach($this->friends as $follower) : ?>
                <?php $tmp = $follower->getFollowedInfo(); ?>
                <a href='<?php echo $this->url(array(
                    "module" => "users",
                    "controller" => "profile",
                    "action" => "view",
                    "id" => $tmp->user_id,
                ),null,true); ?>'><?php echo $tmp->user_name ?></a><br/>
            <?php endforeach; ?>
        <?php else : ?>
            <h3><?php echo $this->translate("You don't have friends!.. Foreveralone...") ?></h3>
        <?php endif; ?>
        <h5><?php echo $this->translate('A user become your friend if he\'s following you and you too.') ?></h5>
        </div>
    </div>
</div>