<?php if( count($this->navigation) ): ?>
    <div class='menu'>
        <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
    </div>
    <div style="clear:both;"></div>
<?php endif; ?>
<?php if(count($this->groups)) : ?>
<?php foreach ($this->groups as $group) : ?>
    <div class="group_info">
        <?php echo $group->group_name ?>
    </div>
<?php endforeach; ?>
<?php else: ?>
    <h3>No groups!</h3>
<?php endif; ?>
<?php if (Engine_Api_Users::getUserInfo()->user_id) : ?>
    <a href="<?php echo $this->url(array(
        "module" => "groups",
        "controller" => "manage",
        "action" => "add",
    ),null,true) ?>">Create a group!</a>
<?php endif; ?>

