<?php if( count($this->navigation) ): ?>
    <div class='menu'>
        <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
    </div>
    <div style="clear:both;"></div>
<?php endif; ?>
<?php if ($this->message) { ?>
<h3><?php echo $this->message; ?></h3>
<?php } ?>
<?php if ($this->form) { ?>
<?php echo $this->form; ?>
<?php } ?>
<?php if ($this->isOk) { ?>
    <h3>Password changed. Use this for the next login: <strong><?php echo $this->newPassword; ?></strong></h3>
<?php } ?>
