<div class="stories">
<table>
    <tr>
<?php foreach ($this->books as $story) :
    $url = $this->url(array(
        "module" => "books",
        "controller" => "stories",
        "action" => "cover",
        "id" => $story->story_id,
        "showCover" => 1
    ),null,true);
    ?>
        <td>
            <div class="storyDetails autoHide">
                <div onclick="window.location.href='<?php echo $url; ?>'" class="cover_mini titoloCover_mini" style="background-color: <?php echo $story->story_bg ?>">
                    <center>
                        <a href='<?php echo $url; ?>'><?php echo (iconv("UTF-8", "UTF-8",$story->story_title)); ?></a>
                    </center>
                </div>
                <div style="display:block">
                    <a href='<?php echo $this->url(array(
                            "module" => "users",
                            "controller" => "wall",
//                            "action" => "view",
                            "id" => $story->story_user_id,
                        ),null,true); ?>'><?php echo $story->getWriter()->user_name ?></a>
                </div>
                <div style="/*position:absolute;*/margin: auto;width:24px;height:24px;background-image: url('<?php echo $this->baseUrl() ?>/contents/images/flags-iso/24/<?php echo $story->story_language ?>.png')"></div>
            </div>
        </td>
<?php endforeach; ?>
    </tr>
</table>
</div>