<?php
$tagsMax = $this->maxtags;
$size100p = 9;//px
//                                    $size100p = 20;//px

$arCustomColors = array();
$arCustomColors[0] = "#8080ff";
$arCustomColors[1] = "#412000";
$arCustomColors[2] = "#806210";
$arCustomColors[3] = "#a160ff";
$arCustomColors[4] = "#080";
$arCustomColors[5] = "#19b92f";
$arCustomColors[6] = "#c600ff";
$arCustomColors[7] = "#ff00d5";
$arCustomColors[8] = "#57ff00";
$arCustomColors[9] = "#f00";
//calcolo size: 100%:SUM = x:COUNT => x% = 100%*COUNT / SUM
//                                $tags = shuffle($tags);
$temp = array();


foreach($this->tags as $tag) :
$size = (int) ($size100p * $tag->tag_counter / $tagsMax);
//$size = (int) ($size100p * $tag->tag_counter / $tagsMax);
//echo $size = (int)($size100p*$tag->story_tag_counter / $tagsUsed);
//printf($translate->_("Today is the %1\$s") . "\n", date('d.m.Y'));
?>
<a
    title="<?php printf($this->translate("Used %1\$s times"),$tag->tag_counter) ?>"
    style="
        color:<?php echo $arCustomColors[$size] ?>;
        font-size: <?php echo 10+$size ?>px;"
    href="<?php echo $this->url(array(
        "module" => "books",
        "controller" => "stories",
        "action" => "showall",
        "tags" => $tag->tag_name,
    )) ?>"><?php echo $tag->tag_name ?></a>
<?php endforeach; ?>
