<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php
    $iconSet = "set1";
    $revision = "0.04";
    ?>
    <title><?php echo ((Zend_Registry::isRegistered('SITE_TITLE')) ? Zend_registry::get('SITE_TITLE') : Engine_Api_Utility::getSiteInfo()->title) ?></title>
    <?php $this->headLink()->appendStylesheet($this->baseUrl()."/contents/css/main.php?{$revision}&baseurl=".$this->baseUrl()."&iconset=".$iconSet); ?>
    <?php $this->headScript()->appendFile($this->baseUrl()."/contents/js/analytics.js"); ?>
    <?php $this->headScript()->appendFile("//ajax.googleapis.com/ajax/libs/dojo/1.8.5/dojo/dojo.js"); ?>
    <?php $this->headScript()->appendFile($this->baseUrl()."/contents/js/init.js?{$revision}"); ?>
    <?php $this->headScript()->appendFile($this->baseUrl()."/contents/js/utility.js?{$revision}"); ?>
    <?php $this->headScript()->appendFile($this->baseUrl()."/contents/js/api/search.js?{$revision}"); ?>
    <?php $this->headScript()->appendFile($this->baseUrl()."/contents/js/api/votes.js?{$revision}"); ?>
    <?php $this->headScript()->appendFile($this->baseUrl()."/contents/js/api/smoothBox.js?{$revision}"); ?>
    <?php $this->headScript()->appendFile($this->baseUrl()."/contents/js/api/works.js?{$revision}"); ?>
    <?php $this->headScript()->appendFile($this->baseUrl()."/contents/js/api/images.js?{$revision}"); ?>
    <?php $this->headScript()->appendFile($this->baseUrl()."/contents/js/api/stream.js?{$revision}"); ?>
    <?php $this->headScript()->appendFile($this->baseUrl()."/contents/js/api/main.js?{$revision}"); ?>

    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
</head>
    <script type="text/javascript">baseUrl = '<?php echo $this->baseUrl() ?>'</script>
    <script type="text/javascript">
reformal_wdg_domain    = "romanzo911";
reformal_wdg_mode    = 0;
reformal_wdg_title   = "roMANZO";
reformal_wdg_ltitle  = "";
reformal_wdg_lfont   = "";
reformal_wdg_lsize   = "";
reformal_wdg_color   = "#";
reformal_wdg_bcolor  = "#516683";
reformal_wdg_tcolor  = "#FFFFFF";
reformal_wdg_align   = "";
reformal_wdg_waction = 0;
reformal_wdg_vcolor  = "#9FCE54";
reformal_wdg_cmline  = "#E0E0E0";
reformal_wdg_glcolor  = "#105895";
reformal_wdg_tbcolor  = "#FFFFFF";

reformal_wdg_bimage = "";

</script>

<body>
    <div id="smoothWindow" class="hide" onclick="Engine_Api_SmootBox.close();"></div><iframe class="hide" id="smoothContent"></iframe>
    <div id="headerMain"></div>
<div>
    <?php // print_r($this->layout()); ?>
    <?php echo $this->layout()->content; ?>
</div>
    <div id="footer">
        <a href="mailto:info[@]storycrossing[.]com">Contact us!</a><br/>
        <?php echo Zend_Db_Table::getDefaultAdapter()->getProfiler()->getTotalNumQueries() ?> queries executed, CPU time: <?php echo number_format(microtime(1) - Engine_Api_Session::getVar("CPUstartTime"),3); ?> seconds.
    </div>
</body>
</html>
