<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->
<?php if ($this->pageCount > 1): ?>
<div class="paginationControl">
<?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
 <?php echo $this->translate('of') ?> <?php echo $this->totalItemCount; ?>

<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->first)); ?>">
    <?php echo $this->translate('First') ?>
  </a> |
<?php else: ?>
  <span class="disabled"><?php echo $this->translate('First') ?></span> |
<?php endif; ?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
    &lt; <?php echo $this->translate('Previous') ?>
  </a> |
<?php else: ?>
  <span class="disabled">&lt; <?php echo $this->translate('Previous') ?></span> |
<?php endif; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
    <?php echo $this->translate('Next') ?> &gt;
  </a> |
<?php else: ?>
  <span class="disabled">Next &gt;</span> |
<?php endif; ?>

<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
    <?php echo $this->translate('Last') ?>
  </a>
<?php else: ?>
  <span class="disabled"><?php echo $this->translate('Last') ?></span>
<?php endif; ?>

</div>
<?php endif; ?>