<?php if( count($this->navigation) ): ?>
  <div class='menu'>
    <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
  </div>
<?php endif; ?>
<?php if( count($this->submenu) ): ?>
  <div class='menu sub' id="subMenu" style="background-color:<?php echo $this->user_preferred_color ?>">
    <?php echo $this->navigation()->menu()->setContainer($this->submenu)->render() ?>
  </div>
<?php endif; ?>
<div id="userContainer">
    <div class="userProfileMenu">
<?php echo $this->render("profile/sidebar.phtml") ?>
    </div>
    <div class="userProfileContainer">
        <div class="blacklist">
        <?php if(count($this->myBlacklist)) : ?>
            <h3>Your blacklist:</h3>
            <?php foreach($this->myBlacklist as $blacklist) : ?>
                <?php $tmp = $blacklist->getUserInfo(); ?>
                <a href='<?php echo $this->url(array(
                    "controller" => "users",
                    "action" => "view",
                    "id" => $tmp->user_id,
                ),null,true); ?>'><?php echo $tmp->user_name ?></a> [<a href='#' onclick='Engine_Api_SmootBox.open("<?php echo $this->url(array(
                            "controller" => "blacklist",
                            "action" => "del",
                            "id" => $tmp->user_id,
                        ),null,true); ?>");return false;'>Remove</a>]<br/>
            <?php endforeach; ?>
        <?php else : ?>
            <h3>Blacklist empty! Go add someone! :D</h3>
        <?php endif; ?>
        </div>
    </div>
</div>