<script type="text/javascript">
function setPageBackGround(selectObj) {
    var which = getSelectValue(selectObj);
    document.getElementById("page_main").setAttribute("style", "background-color: "+which);
}
function setCapital(selectObj) {
    var which = getSelectValue(selectObj);
    document.getElementById("capitalLetter").setAttribute("style","background-image: url('<?php echo $this->baseUrl()?>/contents/images/fonts/"+which+"/a.png')");
}
</script>
<?php if( count($this->navigation) ): ?>
    <div class='menu'>
        <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
    </div>
    <div style="clear:both;"></div>
<?php endif; ?>
<?php if (count($this->stack)) : ?>
    <div class="stack">
        <?php echo $this->navigation()->menu()->setContainer($this->stack)->render(); ?>
    </div>
    <div style="clear:both;"></div>
<?php endif; ?>
    <div id="pageContainer">
<?php if($this->prevPage) : ?>
    <div id="prev_page" style="background-color: <?php echo $this->prevPage->page_bg?>">
        <div class="content">
            <h3><?php echo $this->prevPage->page_title; ?></h3>
            <?php echo nl2br($this->prevPage->page_text); ?>
        </div>
    </div>
<?php endif; ?>
    <div id ="page_main"><div id="capitalLetter"></div><?php echo $this->form; ?></div>
    </div>
    <script type="text/javascript">
        //prendo tutte le options e gli schiaffo un colore
        //document.getElementById('select_page_bg')
        var items = document.getElementById('select_page_bg').getElementsByTagName("option");
        var o;
        for (var i=0;i<items.length;i++) {
            o = items[i];
            o.setAttribute("style","background-color:"+o.value);
            o.innerHTML = "&nbsp;&nbsp;&nbsp;"
        }
        //
        setPageBackGround(document.getElementById('select_page_bg'));
        setCapital(document.getElementById('select_page_capital_font'));
    </script>