<?php if (count($this->users)) : ?>
<?php    foreach ($this->users as $k => $user) : ?>
<a href="<?php echo $this->url(array(
    "module" => "users",
    "controller" => "wall",
    "id" => $user->user_id,
),null,true) ?>"><?php echo $user->user_name ?></a><?php echo ($k < count($this->users)-1) ? ", ":"" ?>
<?php    endforeach; ?>
<?php else : ?>
<b><?php echo $this->translate('Nobody') ?></b>
<?php endif; ?>