<?php if( count($this->navigation) ): ?>
    <div class='menu'>
        <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
    </div>
    <div style="clear:both;"></div>
<?php endif; ?>
    <div class="groups">
<?php if (Engine_Api_Users::getUserInfo()->user_id) : ?>
    <a href="<?php echo $this->url(array(
        "module" => "groups",
        "controller" => "manage",
        "action" => "add",
    ),null,true) ?>"><?php $this->translate("Create a group") ?></a>
<?php endif; ?>
<?php if(count($this->groups)) : ?>
<?php foreach ($this->groups as $group) : ?>
<?php   $url = $this->url(array(
            "module" => "groups",
            "controller" => "view",
            "action" => "one",
            "id" => $group->group_id,
        ),null,true) ?>
        <div class="info" onclick="window.location.href='<?php echo $url ?>'">
            <div class="details">
                <div class="title">
                    <a href="<?php echo $url ?>">
                        <?php echo $group->group_name ?>
                    </a> -
                    <?php
                    switch ($group->group_type) {
                        case 1:
                            echo $this->translate("open");
                            break;
                        case 2:
                            echo $this->translate("readonly");
                            break;
                    }
                    ?>
                </div>
                <div class="description">
                    <?php echo $group->group_desc ?>
                </div>
            </div>
            <div class="users">
                <?php echo sprintf($this->translate("GROUPS_INFO"),$group->getCountBooks(),$group->getCountWriters()) ?>
            </div>
            <div style="clear: both"></div>
<?php /* ?>
            <div class="footer">
                <div class="left">
<?php if (Engine_Api_Users::getUserInfo()->user_id) : ?>
<?php if (Engine_Api_Groups::isAdmin(Engine_Api_Users::getUserInfo()->user_id,$group->group_id)) : ?>
                    <a href="<?php echo $this->url(array(
                        "module" => "groups",
                        "controller" => "edit",
                        "action" => "index",
                        "id" => $group->group_id,
                    ),null,true) ?>"><?php echo $this->translate("manage") ?></a>
<?php endif; ?>
<?php endif; ?>
                </div>
                <div class="right">
<?php if (Engine_Api_Users::getUserInfo()->user_id) : ?>
<?php   if (Engine_Api_Groups::isMemberOf(Engine_Api_Users::getUserInfo()->user_id,$group->group_id)) : ?>
<?php       if (!Engine_Api_Groups::isAdmin(Engine_Api_Users::getUserInfo()->user_id,$group->group_id)) : ?>
                    <a href="" onclick="Engine_Api_SmootBox.open('<?php echo $this->url(array(
                        "module" => "groups",
                        "controller" => "manage",
                        "action" => "leave",
                        "id" => $group->group_id,
                    ),null,true) ?>');return false;"><?php echo $this->translate("Leave this group") ?></a>
<?php       else : ?>
                    <b><?php echo $this->translate("Your group") ?></b>
<?php       endif; ?>
<?php   else : ?>
                    <a href="" onclick="Engine_Api_SmootBox.open('<?php echo $this->url(array(
                        "module" => "groups",
                        "controller" => "manage",
                        "action" => "join",
                        "id" => $group->group_id,
                    ),null,true) ?>');return false;"><?php echo $this->translate("JoinGroup") ?></a>
<?php   endif; ?>
<?php else : ?>
                    <b><?php echo $this->translate("Login to Join") ?></b>
<?php endif; ?>
                </div>
                <div style="clear: both"></div>
            </div>
<?php */ ?>
        </div>
<?php endforeach; ?>
<?php else: ?>
    <h3><?php echo $this->translate("No groups") ?></h3>
<?php endif; ?>
    </div>
