<?php if (count($this->navigation)): ?>
    <div class='menu'>
        <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
    </div>
<?php endif; ?>
<?php if (count($this->submenu)): ?>
    <div class='menu sub' id="subMenu" style="background-color:<?php echo $this->user_preferred_color ?>">
        <?php echo $this->navigation()->menu()->setContainer($this->submenu)->render() ?>
    </div>
<?php endif; ?>
<div id="userContainer">
    <div class="userProfileMenu">
<?php echo $this->render("profile/sidebar.phtml") ?>
    </div>
    <div class="userProfileContainer">
        <div class="blacklist">
            <h3><?php echo $this->translate('Bookmarks') ?></h3>
            <?php if ($this->deleted) : ?>
                <h3 style="color:red;"><?php echo $this->translate('Item deleted!') ?></h3>
                <?php endif; ?>
                <?php if (count($this->bookmarks)) : ?>
                <ul>
                        <?php foreach ($this->bookmarks as $bookmark) : ?>
                        <li>
                            <a href='<?php
                            echo $this->url(array(
                                "module" => "users",
                                "controller" => "bookmarks",
                                "action" => "show",
                                "id" => $bookmark->bookmark_id
                                    ), null, true);
                            ?>'><?php echo $bookmark->bookmark_name; ?></a> [<a href='' onclick='if (!confirm("<?php echo $this->translate("Confirm?")?>")){return false;}Engine_Api_SmootBox.open("<?php
                       echo $this->url(array(
                           "module" => "users",
                           "controller" => "bookmarks",
                           "action" => "del",
                           "id" => $bookmark->bookmark_id,
                               ), null, true);
                       ?>");return false;'>X</a>]
                        </li>
    <?php endforeach; ?>
                </ul>
<?php else : ?>
                <h3><?php echo $this->translate('No bookmarks!') ?></h3>
<?php endif; ?>
        </div>
    </div>
    <div class="clear:both"></div>
</div>
