<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Story Crossing</title>
        <style>
            .homepage {

            }
            body {
                background: url('<?php echo $this->baseUrl() ?>/contents/images/home/wood-floor.jpeg') repeat fixed center;
                width:100%;
                height:100%;
            }
            .homepage .book {
                background: url('<?php echo $this->baseUrl() ?>/contents/images/home/open-book_ok.png') no-repeat center;
                background-size: contain;
                width:800px;
                height:600px;
                margin: auto;
            }
            .homepage .font {
                font-family: 'Seaweed Script', cursive;
				text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;
            }
            .homepage .page {
                float:left;
                margin-top:50px;
                width: 330px;
                height: 500px;
            }
			.homepage .page .font {
				text-shadow:none;
			}
            .homepage .page A {
                text-transform: none;
                text-decoration: none;
                color: black;
                font-weight: bold;
            }
            .homepage .page .header {

            }
            .homepage .page .title {
                font-weight: bold;
                font-size: 18px;
                padding-top: 10px;
                padding-bottom: 10px;
            }
            .homepage .page .text {
                height: 340px;
                color: gray;
                cursor: pointer;
                text-align: justify;
            }
            .homepage #pgSx {
                margin-left:50px;
            }
            .homepage #pgDx {
                margin-left: 30px;
            }
        </style>
        <link href='http://fonts.googleapis.com/css?family=Seaweed+Script' rel='stylesheet' type='text/css' />
    </head>
    <body>
        <div class="homepage">
            <div class="desk">
                <div>
                    <div style="padding-top:20px;margin:auto;width:800px;text-align: center">
                        <div style="text-align: right;margin-right: -60px">
                            <img onclick="window.location.href='<?php echo $this->url(array(
                                    "module" => "users",
                                    "controller" => "auth",
                                    "action" => "loginfacebook",
                                ),null,true) ?>'" style="cursor:pointer;width:200px" src="<?php echo $this->baseUrl() ?>/contents/images/home/facebook_connect.png"/>
                            <br/>
                            <a style="color:white;font-size: 20px;margin-right: 10px;" href="<?php echo $this->url(array(
                                        "module" => "users",
                                        "controller" => "auth",
                                        "action" => "login",
                                    ),null,true) ?>">
                                Login
                            </a>
                        </div>
                        <div style="width:100%;font-size: 75px;color: wheat;margin-top: -60px" class="font">
                            StoryCrossing
                        </div>
                        <div class="font" style="font-size:28px;color:wheat;padding-top:10px;">
                            una community di scrittura collaborativa per chi ama<br/>
                            raccontare storie con amici o persone nuove
                        </div>
                    </div>
                </div>
                <div class="book">
                    <div class="page" id="pgSx">
                        <div class="header font" style="font-size:30px;color:grey">
                            Tra i racconti piu' votati ...
                        </div>
                        <div class="title">
                            <?php echo Engine_Api_Session::getVar("sx_title") ?>
                        </div>
                        <div class="text" onclick="window.location.href='<?php echo $this->url(array(
                            "module" => "books",
                            "controller" => "stories",
                            "action" => "cover",
                            "id" => Engine_Api_Session::getVar("sx_id"),
                            "showCover" => 1
                        ),null,true) ?>'">
                            <?php
                            $text = Engine_Api_Session::getVar("sx_text");
                            if (strlen($text) > 850) {
                                $text = substr($text, 0, 850) . " [...]";
                            }
                            echo $text;
                            ?>
                        </div>
                        <div class="replies">
                            <a href='<?php echo $this->url(array(
                                "module" => "books",
                                "controller" => "stories",
                                "action" => "view",
                    //            "id" => $this->page->page_story_id,
                                "idpage" => Engine_Api_Session::getVar("sx_reply_id_1"),
                            ),null,true)?>'>
                                <?php echo Engine_Api_Session::getVar("sx_reply_1") ?>
                            </a><br/>
                            <a href='<?php echo $this->url(array(
                                "module" => "books",
                                "controller" => "stories",
                                "action" => "view",
                    //            "id" => $this->page->page_story_id,
                                "idpage" => Engine_Api_Session::getVar("sx_reply_id_2"),
                            ),null,true)?>'>
                                <?php echo Engine_Api_Session::getVar("sx_reply_2") ?>
                            </a><br/>
                            <a href='<?php echo $this->url(array(
                                "module" => "users",
                                "controller" => "auth",
                                "action" => "login",
                            ),null,true)?>'>Aggiungi tu una continuazione</a>
                        </div>
                        <div style="clear:both"></div>
                    </div>
                    <div class="page" id="pgDx">
                        <div class="header font" style="font-size:30px;color:grey">
                            Tra i nuovi racconti ...
                        </div>
                        <div class="title">
                            <?php echo Engine_Api_Session::getVar("dx_title") ?>
                        </div>
                        <div class="text" onclick="window.location.href='<?php echo $this->url(array(
                            "module" => "books",
                            "controller" => "stories",
                            "action" => "cover",
                            "id" => Engine_Api_Session::getVar("dx_id"),
                            "showCover" => 1
                        ),null,true) ?>'">
                            <?php
                            $text = Engine_Api_Session::getVar("dx_text");
                            if (strlen($text) > 850) {
                                $text = substr($text, 0, 850) . " [...]";
                            }
                            echo $text;
                            ?>
                        </div>
                        <div class="replies">
                            <a href='<?php echo $this->url(array(
                                "module" => "books",
                                "controller" => "stories",
                                "action" => "view",
                    //            "id" => $this->page->page_story_id,
                                "idpage" => Engine_Api_Session::getVar("dx_reply_id_1"),
                            ),null,true)?>'>
                                <?php echo Engine_Api_Session::getVar("dx_reply_1") ?>
                            </a><br/>
                            <a href='<?php echo $this->url(array(
                                "module" => "books",
                                "controller" => "stories",
                                "action" => "view",
                    //            "id" => $this->page->page_story_id,
                                "idpage" => Engine_Api_Session::getVar("dx_reply_id_2"),
                            ),null,true)?>'>
                                <?php echo Engine_Api_Session::getVar("dx_reply_2") ?>
                            </a><br/>
                            <a href='<?php echo $this->url(array(
                                "module" => "users",
                                "controller" => "auth",
                                "action" => "login",
                            ),null,true)?>'>Aggiungi tu una continuazione</a>
                        </div>
                        <div style="clear:both"></div>
                    </div>
                    <div style="clear:both"/>
                </div>
            </div>
        </div>
    </body>
</html>

