<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>StoryCrossing</title>
    <?php $iconSet = "set1"; ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl()."/contents/css/main.php?baseurl=".$this->baseUrl()."&iconset=".$iconSet); ?>
    <?php $this->headScript()->appendFile($this->baseUrl()."/contents/js/analytics.js"); ?>
    <?php $this->headScript()->appendFile($this->baseUrl()."/contents/js/dojo/dojo.js"); ?>
    <?php $this->headScript()->appendFile($this->baseUrl()."/contents/js/init.js"); ?>
    <?php $this->headScript()->appendFile($this->baseUrl()."/contents/js/popup.js"); ?>


    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
</head>
    <body>
    <?php echo $this->layout()->content; ?>
    </body>
</html>