<?php if( count($this->navigation) ): ?>
  <div class='menu'>
    <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
  </div>
<?php endif; ?>
<div class="groups">

    <h3>Utenti: <?php echo $this->group->group_name ?></h3>

<?php echo $this->render("edit/sidebar.phtml") ?>
    <div class="content">
<?php if (count($this->readers)) : ?>
    <ul>
<?php foreach($this->readers as $reader) : ?>
        <li>
            <?php echo $reader->getInfo()->user_name ?>
            <?php
            $level = Engine_Api_Groups::getLevelOf($reader->getInfo()->user_id,$this->group->group_id);
            if ($level) : ?>
                <i>(<?php echo $level ?>)</i>
<?php       endif; ?>
<?php       switch ($level) : ?>
<?php           case "owner": ?>
<?php           break; ?>
<?php           case "admin": ?>
                <a href="" onclick="Engine_Api_SmootBox.open('<?php echo $this->url(array(
                        "module" => "groups",
                        "controller" => "users",
                        "action" => "set",
                        "type" => "writer",
                        "idGroup" => $this->group->group_id,
                        "idUser" => $reader->getInfo()->user_id,
                    ),null,true) ?>');return false;">Rimuovi da admin</a>
<?php           break; ?>
<?php           case "writer": ?>
                <a href="" onclick="Engine_Api_SmootBox.open('<?php echo $this->url(array(
                        "module" => "groups",
                        "controller" => "users",
                        "action" => "set",
                        "type" => "admin",
                        "idGroup" => $this->group->group_id,
                        "idUser" => $reader->getInfo()->user_id,
                    ),null,true) ?>');return false;">Promuovi come admin</a> |
                <a href="" onclick="Engine_Api_SmootBox.open('<?php echo $this->url(array(
                        "module" => "groups",
                        "controller" => "users",
                        "action" => "set",
                        "type" => "regular",
                        "idGroup" => $this->group->group_id,
                        "idUser" => $reader->getInfo()->user_id,
                    ),null,true) ?>');return false;">Togli dagli scrittori</a>
<?php           break; ?>
<?php           default: ?>
                    <a href="" onclick="Engine_Api_SmootBox.open('<?php echo $this->url(array(
                        "module" => "groups",
                        "controller" => "users",
                        "action" => "set",
                        "type" => "writer",
                        "idGroup" => $this->group->group_id,
                        "idUser" => $reader->getInfo()->user_id,
                    ),null,true) ?>');return false;">Promuovi a scrittore</a>
<?php       endswitch; ?>
        </li>
<?php endforeach; ?>
    </ul>
<?php endif; ?>
    </div>
    <div style="clear:both"></div>
</div>
