<?php
Zend_Registry::set("SITE_TITLE",$this->userDetails->user_name ."'profile | ".Engine_Api_Utility::getSiteInfo()->title);
$isMe = Engine_Api_Users::getUserInfo()->user_id == $this->userDetails->user_id;
switch (true) {
    case (Engine_Api_Users::getUserInfo()->user_id && !$isMe) :
        $followable = true;
        break;
    default:
        $followable = false;
}
$tF = new Users_Model_DbTable_Followers();
if ($followable && $tF->isFollowing(Engine_Api_Users::getUserInfo()->user_id, $this->userDetails->user_id)) {
    $followed = true;
} else {
    $followed = false;
}
?>
<div>
        <h3><?php echo sprintf($this->translate('USER_PROFILE_NAME'),$this->userDetails->user_name) ?></h3>
<?php if (!empty($this->userDetails->user_fb_id)) : ?>
        <a href="<?php echo $this->userDetails->user_fb_profile ?>" target="_blank">
            <img src='https://graph.facebook.com/<?php echo $this->userDetails->user_fb_id ?>/picture' title="Go to Facebook profile!"/>
        </a><br/>
<?php endif; ?>
<?php if (!$isMe && Engine_Api_Users::getUserInfo()->user_id) : ?>
        <a href="<?php echo $this->url(array(
            "module" => "users",
            "controller" => "profile",
            "action" => "view",
        ),null,true) ?>"><?php echo $this->translate('Back to my profile') ?></a><hr/>
<?php endif; ?>
    </div>
<?php if ($followable) : ?>
<?php if (!$followed) { ?>
        <?php $uri = $this->url(array(
                            "module" => "users",
                            "controller" => "followers",
                            "action" => "add",
                            "idwriter" => $this->userDetails->user_id,
                        ),null,true); ?>
<a href='' target='_blank' onclick="Engine_Api_SmootBox.open('<?php echo $uri; ?>');return false;" ><?php echo $this->translate('Follow!') ?></a>
    <?php } else { ?>
        <?php $uri = $this->url(array(
                            "module" => "users",
                            "controller" => "followers",
                            "action" => "del",
                            "idwriter" => $this->userDetails->user_id,
                        ),null,true); ?>
<a href='#' target='_blank' onclick="Engine_Api_SmootBox.open('<?php echo $uri; ?>');return false;"><?php echo $this->translate('Unfollow!') ?></a>
    <?php } ?>
<?php else : //isme? ?>
<?php   if ($isMe) : ?>
<a href="<?php echo $this->url(array(
    "module" => "users",
),null,true) ?>"><?php echo $this->translate('Edit!') ?></a><hr/>
<a href="<?php echo $this->url(array(
    "module" => "users",
    "controller" => "blacklist",
),null,true) ?>"><?php echo $this->translate("Blacklist") ?></a><br/>
<a href="<?php echo $this->url(array(
    "module" => "users",
    "controller" => "bookmarks",
),null,true) ?>"><?php echo $this->translate("Bookmarks") ?></a>
<hr/>
<?php   else : ?>
<?php   endif; ?>
<?php endif; ?>
<div class="userDetails">
<?php $string = $isMe ? "USER_YOU_WROTE_X_STORIES" : "USER_WROTE_X_STORIES";
echo sprintf($this->translate($string),$this->userDetails->getDetails()->countStories) ?><br/>

<?php $string = $isMe ? "USER_YOU_WROTE_X_PAGES" : "USER_WROTE_X_PAGES";
echo sprintf($this->translate($string),$this->userDetails->getDetails()->countPages) ?><br/>

<?php $string = $isMe ? "USER_YOU_ARE_FOLLOWEDBY_X_USERS" : "USER_FOLLOWEDBY_X_USERS";
echo sprintf($this->translate($string),$this->userDetails->getDetails()->countFollowers) ?><br/>

<?php $string = $isMe ? "USER_YOU_ARE_FOLLOWING_X_USERS" : "USER_FOLLOWING_X_USERS";
echo sprintf($this->translate($string),$this->userDetails->getDetails()->countFollowing) ?><br/>

<?php $string = $isMe ? "USER_YOU_READ_X_PAGES" : "USER_READ_X_PAGES";
echo sprintf($this->translate($string),$this->userDetails->getDetails()->countPagesRead) ?><br/>

<?php $string = $isMe ? "USER_YOU_VOTED_X_PAGES" : "USER_VOTED_X_PAGES";
echo sprintf($this->translate($string),$this->userDetails->getDetails()->countVotes) ?><br/>

</div>