<?php if( count($this->navigation) ): ?>
  <div class='menu'>
    <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
  </div>
<?php endif; ?>
<?php if( count($this->submenu) ): ?>
  <div class='menu sub' id="subMenu" style="background-color:<?php echo $this->user_preferred_color ?>">
    <?php echo $this->navigation()->menu()->setContainer($this->submenu)->render() ?>
  </div>
<?php endif; ?>
<div id="userContainer">
<div class="userProfileMenu">
<?php echo $this->render("profile/sidebar.phtml") ?>
</div>
    <div class="userProfileContainer">
        <div class="followers">
        <?php if (count($this->myFollowers)) : ?>
            <h3><?php echo $this->translate('Followers') ?>:</h3>
            <?php foreach($this->myFollowers as $follower) : ?>
                <?php $tmp = $follower->getInfo(); ?>
                <a href='<?php echo $this->url(array(
                    "module" => "users",
                    "controller" => "profile",
                    "action" => "view",
                    "id" => $tmp->user_id,
                ),null,true); ?>'><?php echo $tmp->user_name ?></a><br/>
            <?php endforeach; ?>
        <?php else : ?>
            <?php if ($this->isMe) : ?>
                <h3>Nobody is following you!</h3>
            <?php else : ?>
                <h3>Nobody is following this user!</h3>
            <?php endif; ?>
        <?php endif; ?>
        </div>
    </div>
</div>