<?php $idGroup = $this->groupInfo->group_id; $group = $this->groupInfo;?>
<div class="sidebarBooks">
<?php if (Engine_Api_Users::getUserInfo()->user_id) : ?>
<?php if (Engine_Api_Groups::isAdmin(Engine_Api_Users::getUserInfo()->user_id,$idGroup)) : ?>
        <a href="<?php echo $this->url(array(
            "module" => "groups",
            "controller" => "edit",
            "action" => "index",
            "id" => $idGroup,
        ),null,true) ?>"><?php echo $this->translate("manage") ?></a><br/>
<?php endif; ?>
<?php endif; ?>

<?php if (Engine_Api_Users::getUserInfo()->user_id) : ?>
<?php   if (Engine_Api_Groups::isMemberOf(Engine_Api_Users::getUserInfo()->user_id,$group->group_id)) : ?>
<?php       if (!Engine_Api_Groups::isAdmin(Engine_Api_Users::getUserInfo()->user_id,$group->group_id)) : ?>
                    <a href="" onclick="Engine_Api_SmootBox.open('<?php echo $this->url(array(
                        "module" => "groups",
                        "controller" => "manage",
                        "action" => "leave",
                        "id" => $group->group_id,
                    ),null,true) ?>');return false;"><?php echo $this->translate("Leave this group") ?></a><br/>
<?php       else : ?>
                    <b><?php echo $this->translate("Your group") ?></b><br/>
<?php       endif; ?>
<?php   else : ?>
                    <a href="" onclick="Engine_Api_SmootBox.open('<?php echo $this->url(array(
                        "module" => "groups",
                        "controller" => "manage",
                        "action" => "join",
                        "id" => $group->group_id,
                    ),null,true) ?>');return false;"><?php echo $this->translate("JoinGroup") ?></a><br/>
<?php   endif; ?>
<?php else : ?>
                    <b><?php echo $this->translate("Login to Join") ?></b><br/>
<?php endif; ?>
</div>