<?php if( count($this->navigation) ): ?>
    <div class='menu'>
        <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
    </div>
    <div style="clear:both;"></div>
<?php endif; ?>
<?php if ($this->error) : ?>
    <h3 style="color:red;font-weight: bold;"><?php echo $this->error; ?></h3>
<?php endif; ?>
<?php if (!$this->isOk) : ?>
<?php echo $this->form; ?>
<?php else :?>
    <h3>Password changed!</h3>
<?php endif; ?>
