<?php if( count($this->navigation) ) : ?>
    <div class='menu'>
        <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
    </div>
    <div style="clear:both;"></div>
<?php endif; ?>
<h2>Fill the form</h2> or
<a href="<?php echo $this->url(array(
    "module" => "users",
    "controller" => "auth",
    "action" => "loginfacebook",
),null,true) ?>">login with Facebook! <img src="<?php echo $this->baseUrl() ?>/contents/images/icons/fb.png" title="login with Facebook!"/>
</a>
<?php if ($this->error) : ?>
<h3 style="color:red;font-weight: bold;"><?php echo $this->error; ?></h3>
<?php endif; ?>
<?php echo $this->form; ?>