<?php if( count($this->navigation) ) : ?>
    <div class='menu'>
        <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
    </div>
    <div style="clear:both;"></div>
<?php endif; ?>
<center>
<?php
$idGroup = 0;
if ($this->groupInfo) :
    $idGroup = $this->groupInfo->group_id;
?>
    <h3><?php echo $this->groupInfo->group_name ?></h3>
<?php endif; ?>
<div id="orderBy" style="margin:auto;padding-left: 200px">
<?php echo $this->form; ?>
</div>
</center>
<div style="clear:both;"></div>
<?php if($idGroup) : ?>
<?php echo $this->render("groups/sidebar.phtml") ?>
    <div>
<?php endif; ?>
<div class="stories">
    <?php if (count($this->stories)) : ?>
        <table>
            <?php
            $i = 0;
            $elementiPerPagine = 4;
            foreach($this->stories as $story) :
                $url = $this->url(array(
                    "module" => "books",
                    "controller" => "stories",
                    "action" => "cover",
                    "id" => $story->story_id,
                    "showCover" => 1
                ),null,true);
                if ($i == 0 || $i % $elementiPerPagine == 0) { ?>
                    <tr>
                <?php } ?>
                        <td><div class="storyDetails autoHide">
                            <div onclick="window.location.href='<?php echo $url; ?>'" class="cover_mini titoloCover_mini" style="background-color: <?php echo $story->story_bg ?>">
                                <center>
                                    <a href='<?php echo $url; ?>'><?php echo (iconv("UTF-8", "UTF-8",$story->story_title)); ?></a>
                                </center>
                            </div>
                            <div style="display:block">
                            <a href='<?php echo $this->url(array(
                                    "module" => "users",
                                    "controller" => "wall",
//                                    "action" => "view",
                                    "id" => $story->story_user_id,
                                ),null,true); ?>'><?php echo $story->getWriter()->user_name ?></a>
                            </div>
                            <div style="/*position:absolute;*/margin: auto;width:24px;height:24px;background-image: url('<?php echo $this->baseUrl() ?>/contents/images/flags-iso/24/<?php echo $story->story_language ?>.png')"></div>
                            </div>
                        </td>
                <?php if (++$i % $elementiPerPagine == 0) { ?>
                    </tr>
                <?php } ?>
            <?php endforeach; ?>
            <?php if (++$i % $elementiPerPagine != 0) { ?>
                </tr>
            <?php } ?>
        </table>
    <?php else : ?>
    <h3><?php echo $this->translate('No stories with seleceted filters!!') ?></h3>
    <?php endif; ?>

    <?php echo $this->paginationControl($this->stories,
        'Elastic',
        'paginators/items.phtml'); ?>
    <div class="button">
    <?php if ($this->isLogged) : ?>
        <div class="image add"></div>
        <a href="<?php echo $this->url(array(
            "module" => "books",
            "controller" => "stories",
            "action" => "add",
            "idgroup" => $idGroup
        ),null,true) ?>"><?php echo $this->translate('Add a story') ?></a>
    <?php else : ?>
    <div class="image error"></div>
    <strong><?php echo $this->translate('You must login to add a story!') ?></strong>
    <?php endif; ?>
    </div>
</div>
<?php if($idGroup) : ?>
    </div>
<?php endif; ?>

