<?php if( count($this->navigation) ): ?>
    <div class='menu'>
        <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
    </div>
    <div style="clear:both;"></div>
<?php endif; ?>
<div id="homepage">
    <div id="logoHover" onclick="window.location.href='<?php echo $this->url(array(
        "module" => "books",
    ),null,true) ?>'"></div>
    <div id="logo">
        <div id="logoShowCase_content"></div>
        <div id="logoInfo"><?php printf($this->translate('subLogoInfo'),
                $this->totBooks,
                $this->totPages,
                $this->totUsers
        ) ?></div>
    </div>
    <div id="cols">
        <div id="col_left">
            <div class="homeBox" id="fbconnect">
                <div class="title">CONNECT WITH FB!</div>
                <div class="content" id="fwconnect_populars_content">
                    <center>
                        <?php if (empty(Engine_Api_Users::getUserInfo()->user_fb_id)) : ?>
                            <a href="<?php echo $this->url(array(
                                "module" => "users",
                                "controller" => "auth",
                                "action" => "loginfacebook",
                            ),null,true) ?>">Login with Facebook!<br/>
                                <img src="<?php echo $this->baseUrl() ?>/contents/images/icons/fb.png" title="Login with Facebook!"/>
                            </a>
                        <?php else: ?>
                            <img src='https://graph.facebook.com/<?php echo Engine_Api_Users::getUserInfo()->user_fb_id ?>/picture' title="Logged in with Facebook!"/>
                        <?php endif; ?>
                    </center>
                </div>
            </div>
            <div class="homeBox" id="fbtw">
                <div class="title">FOLLOW US!</div>
                <div class="content" id="fwtw_populars_content">
                    <center>
                        <a href="https://www.facebook.com/pages/StoryCrossing/193163700794559" target="_blank">
                            <img src="<?php echo $this->baseUrl() ?>/contents/images/icons/fb.png" title="Follow us on Facebook!"/>
                        </a>
                        <a href="https://twitter.com/storycrossing1" target="_blank">
                            <img src="<?php echo $this->baseUrl() ?>/contents/images/icons/tw.png" title="Follow us on Twitter!"/>
                        </a>
                    </center>
                </div>
            </div>
            <div class="homeBox" id="tags_populars">
                <div class="title">TAGS</div>
                <div class="content" id="tags_populars_content"><?php echo $this->translate('Loading...') ?></div>
            </div>
            <div class="homeBox" id="lastOnlineUsers">
                <div class="title">USERS ONLINE</div>
                <div class="content" id="lastOnlineUsers_content"><?php echo $this->translate('Loading...') ?></div>
            </div>
        </div>
        <div id="col_middle">
            <div class="homeBox" id="news_last">
                <div class="title">NEWS</div>
                <div class="content" id="news_content">
                Benvenuti su StoryCrossing. Un sito di scrittura collaborativa! Buona permanenza!<br/>
                <br/>
                StoryCrossing incontra il robottino verde. A breve, nel market di Android! :)</div>
            </div>
            <div class="homeBox" id="activity_last">
                <div class="title"><?php echo $this->translate('RECENT ACTIVITY') ?></div>
                <div class="content" id="activity_last_content"></div>
            </div>
        </div>
        <div id="col_right">
            <div class="homeBox" id="writers_top_weekly">
                <div class="title"><?php echo $this->translate('TOP WRITERS OF THE WEEK') ?></div>
                <div class="content" id="writers_top_weekly_content"><?php echo $this->translate('Loading...') ?></div>
            </div>
            <div class="homeBox" id="writers_top_all">
                <div class="title"><?php echo $this->translate('TOP WRITERS OF ALL TIME') ?></div>
                <div class="content" id="writers_top_ever_content"><?php echo $this->translate('Loading...') ?></div>
            </div>
            <!--<div class="homeBox" id="activity_top10books">
                <div class="title">TOP 10 BOOKS</div>
                <div class="content">Qui compariranno i 10 libri piu' belli secondo i lettori</div>
            </div>-->
            <div class="homeBox" id="activity_top10writers">
                <div class="title">TOP 10 WRITERS</div>
                <div class="content" id="writers_most_followed"><?php echo $this->translate('Loading...') ?></div>
            </div>
        </div>
        <div style="clear:both;"></div>
    </div>
</div>
<script type="text/javascript">
    Engine_Api_Stream.getStream('activity_last_content');
    Engine_Api_Main.getTags('tags_populars_content');
    Engine_Api_Main.getTopWriters('writers_top_weekly_content');
    Engine_Api_Main.getTopWritersEver('writers_top_ever_content');
    Engine_Api_Main.mostFollowed('writers_most_followed');
    Engine_Api_Main.getLastActiveUsers('lastOnlineUsers_content');
    Engine_Api_Main.getShowCase('logoShowCase_content');
</script>