<?php if( count($this->navigation) ): ?>
    <div class='menu'>
        <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
    </div>
    <div style="clear:both;"></div>
<?php endif; ?>
<?php if (count($this->stack)) : ?>
    <div class="stack">
        <?php echo $this->navigation()->menu()->setContainer($this->stack)->render(); ?>
    </div>
    <div style="clear:both;"></div>
<?php endif; ?>
<?php if ($this->page) : ?>
<?php Zend_Registry::set("SITE_TITLE",$this->page->page_title ." | ".Engine_Api_Utility::getSiteInfo()->title) ?>
    <div id="pageContainer">
    <?php if ($this->prevPage) : ?>
        <div id="prev_page" style="/*font-family: 'Special Elite', cursive;font-size:14px;*/background-color: <?php echo $this->prevPage->page_bg?>;">
            <div class="bubble"></div>
            <div class="content">
                <h3><?php echo (iconv("UTF-8", "UTF-8",$this->prevPage->page_title)); ?></h3>
                <?php if ($this->prevPageFirstLetter) { ?>
                <div class="pageFirstLetter"><img src='<?php echo $this->baseUrl() ?>/contents/images/fonts/<?php echo $this->prevPageFontFamily ?>/<?php echo $this->prevPageFirstLetter ?>'/></div>
                <?php } ?>
                <?php echo nl2br(iconv("UTF-8", "UTF-8",$this->prevPage->page_text)); ?>
            </div>
        </div>
    <?php endif; ?>
    <div id="page_main" style="/*font-family: 'Special Elite', cursive;font-size:14px;*/background-color: <?php echo $this->page->page_bg?>;">
        <h6><?php
            $icon = "";
            if($this->page->page_from_mobile != 0) :
                switch ($this->page->page_from_mobile) {
                    case 1:
                        $icon = "android.png";
                        break;
                }
            endif; ?>
            <?php if($icon != "") : ?><img src='<?php echo $this->baseUrl() ?>/contents/images/icons/<?php echo $icon ?>' style="width:20px;height:20px" /><?php endif; ?>
            <?php echo $this->translate('Wrote by') ?> <?php echo $this->translate($this->isOwner ? "you" : $this->page->getUserInfo()->user_name); ?> (<?php echo $this->translate($this->page->getDateAdvancedFormat()); ?>)
            <?php if ($this->isLogged) : ?>
                <?php if ($this->followable) : ?><br/>[
                    <?php if ($this->following) : ?>
                        <?php $uri = $this->url(array(
                            "module" => "users",
                            "controller" => "followers",
                            "action" => "del",
                            "idwriter" => $this->page->getUserInfo()->user_id,
                        ),null,true); ?>
                        <strong><?php echo $this->translate('Following!') ?></strong>
                        | <a href='#' target='_blank' onclick="Engine_Api_SmootBox.open('<?php echo $uri; ?>');return false;"><?php echo $this->translate('Unfollow!') ?></a>
                    <?php else : ?>
                        <?php $uri = $this->url(array(
                            "module" => "users",
                            "controller" => "followers",
                            "action" => "add",
                            "idwriter" => $this->page->getUserInfo()->user_id,
                        ),null,true); ?>
                        <a href='' target='_blank' onclick="Engine_Api_SmootBox.open('<?php echo $uri; ?>');return false;" ><?php echo $this->translate("Follow!"); ?></a>
                    <?php endif; ?>]
                <?php endif; ?>
            <?php endif; ?>
        </h6>
        <div class="content">
            <h2><?php echo (iconv("UTF-8", "UTF-8",$this->page->page_title)); ?></h2>
            <?php if ($this->pageFirstLetter) { ?>
            <div class="pageFirstLetter"><img src='<?php echo $this->baseUrl() ?>/contents/images/fonts/<?php echo $this->fontFamily ?>/<?php echo $this->pageFirstLetter ?>'/></div>
            <?php } ?>
            <?php echo nl2br((iconv("UTF-8", "UTF-8",$this->page->page_text))); ?><br/>
<?php if ($this->isLogged && !$this->alreadyVoted && !$this->isOwner) {
    $urlVoto = $this->url(array(
        "module" => "books",
        "controller" => "pagevotes",
        "action" => "vote",
        "idpage" => $this->page->page_id,
    ),null,true);
    ?>
    <i><?php echo $this->translate('Vote this page!') ?></i>
        <a href='#' onclick="Engine_Api_SmootBox.open('<?php echo $urlVoto ?>/vote/up');return false;"><img src="<?php echo $this->baseUrl() ?>/contents/images/icons/thumbup.gif"/></a>
        <a href='#' onclick="Engine_Api_SmootBox.open('<?php echo $urlVoto ?>/vote/down');return false;"><img src="<?php echo $this->baseUrl() ?>/contents/images/icons/thumbdown.gif"/></a>
<?php }
if ($this->votes["down"] + $this->votes["up"]) :
?>
    <br/><i><?php printf($this->translate("PAGE_VOTES_REPORT"), $this->votes["up"], $this->votes["down"] + $this->votes["up"]); ?></i>
<?php endif; ?>
        </div>
<?php $n = 1; ?>
<div class="queries">
    <span class="bold"><?php echo $this->translate('Choose how this story should continue...') ?></span><br/>
<?php if (count($this->page_queries)) : ?>
    <?php foreach ($this->page_queries as $query) : ?>
        <div class='<?php echo $query->isWriterInMyBlacklist() ? "query blacklisted" : "query" ?>'>
        <?php echo $n++; ?>).
        <a href="<?php echo $this->url(array(
            "module" => "books",
            "controller" => "stories",
            "action" => "view",
//            "id" => $this->page->page_story_id,
            "idpage" => $query->page_id,
        ),null,true); ?>">
                <?php echo $query->page_title ?>
        </a><br/>
        <?php if(!empty($query->votes)) : ?>
        <?php /*echo $this->translate('Voted') ?> <?php echo number_format($query->votes,1) */?>
        <?php printf($this->translate("PAGE_VOTES_REPORT"), $query->votesUp, $query->votesUp + $query->votesDown) ?>
        <?php else : ?>
        <?php echo $this->translate('Not voted') ?>,
        <?php endif; ?>
         <?php printf($this->translate('clicked by %s% of readers'),$query->getPercentage()) ?> <i>[by
            <a href='<?php echo $this->url(array(
                "module" => "users",
                "controller" => "profile",
                "action" => "view",
                "id" => $query->getUserInfo()->user_id,
            ),null,true); ?>'><?php echo $query->getUserInfo()->user_name ?></a>]</i>
        </div><hr/>
    <?php endforeach; ?>
<?php endif; ?>
<br/>
<?php if ($this->isLogged) {
    $userLevel = @Engine_Api_Groups::getLevelOf(Engine_Api_Users::getUserInfo()->user_id, $this->page->getGroup()->group_id);
    if (!$this->page->getGroup() || @$this->page->getGroup()->group_type == 1 || ($userLevel != null)) : ?>
    <a class="bold" style="margin-top:10px;" href="<?php echo $this->url(array(
        "module" => "books",
        "controller" => "pages",
        "action" => "add",
        "idstory" => $this->page->page_story_id,
        "idparent" => $this->page->page_id,
    ),null,true) ?>"><?php echo $this->translate('Add a page') ?></a>
<?php else: ?>
        <strong>Gruppo in sola lettura! Solo i membri possono scrivere!</strong>
<?php endif; ?>
    <?php } else { ?>
        <strong><?php echo $this->translate('You must login to add a page!') ?></strong>
    <?php } ?>
</div>

    </div>
    <div style="clear:both;"></div>
    <div id="bottombar">
<!-- AddThis Button BEGIN -->
<div style="width:400px;margin:auto" class="addthis_toolbox addthis_default_style addthis_32x32_style">
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>
<a class="addthis_button_compact"></a>
<a class="addthis_counter addthis_bubble_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4ea83dd8482740cc"></script>
<!-- AddThis Button END -->
<!--        <a
            href="#"
            onclick="
                if(dojo.byId('sidebarContainer').getAttribute('style').match(/block/)) {
                    dojo.byId('sidebarContainer').setAttribute('style','display:none;');
                } else {
                    dojo.byId('sidebarContainer').setAttribute('style','display:block;');
                }
                return false;"
        ><b><?php echo $this->translate('Show/Hide sidebar') ?></b></a>-->
        <div id="sidebarContainer" style="display:block">
<?php printf($this->translate('This page has been read %s times.'),$this->totReads) ?><br/>
<?php /*echo $this->translate('Medium vote') ?>: <b><?php echo $this->votes["medium"] ?></b><br/> */ ?>
<?php if ($this->isLogged) { ?>
<hr/><a href="" onclick="Engine_Api_SmootBox.open('<?php echo $this->url(array(
    "module" => "books",
    "controller" => "reporttoadmins",
    "action" => "page",
    "id" => $this->page->page_id,
),null,true) ?>') ;return false;"><?php echo $this->translate("Report page") ?></a><br/>
<!--<br/>
<?php echo $this->translate("Share with...") ?>
<select onchange="Engine_Api_SmootBox.open('<?php echo $this->url(array(
    "module" => "users",
    "controller" => "sharer",
    "action" => "share"
),null,true) ?>/with/'+getSelectValue(this)+'/what/page/idobj/<?php echo $this->page->page_id ?>')">
    <option></option>
    <option value="friends">friends</option>
    <option value="group">group</option>
    <option value="followers">followers</option>
</select>-->
    <hr/>
<?php if($this->canEdit) : ?>
    <a href="<?php echo $this->url(array(
        "module" => "books",
        "controller" => "pages",
        "action" => "edit",
        "id" => $this->page->page_id,
    ),null,true) ?>"><?php echo $this->translate('Edit!') ?></a>
    <hr/>
<?php endif; ?>
    <?php if (!$this->bookmarked) { ?>
        <div class="button">
            <div class="image pin"></div>
        <a href="#" onclick="Engine_Api_SmootBox.open('<?php echo $this->url(array(
            "module" => "users",
            "controller" => "bookmarks",
            "action" => "add",
            "idpage" => $this->page->page_id,
            "idstory" => $this->page->page_story_id,
        ),null,true); ?>');return false;"><?php echo $this->translate('Bookmark this page!') ?></a>
        </div>
    <?php } ?>
    <?php if (!$this->isOwner) : ?>
        <div class="button">
            <div class="image remove"></div>
            <?php
            if ($this->writerAlreadyBlocked) {
                $actionLock = "del";
                $textLock = $this->translate("Unblock user");
            } else {
                $actionLock = "add";
                $textLock = $this->translate("Block user");
            }
            ?>
            <a href='#' onclick='Engine_Api_SmootBox.open("<?php echo $this->url(array(
                "module" => "users",
                "controller" => "blacklist",
                "action" => $actionLock,
                "id" => $this->page->page_user_id,
            ),null,true); ?>");return false;'><?php echo $textLock; ?></a>
        </div>
    <?php endif; ?>
<?php } ?>
    <hr/>
    <?php if ($this->page->page_prev_page_id) { ?>
        <a href="<?php echo $this->url(array(
            "module" => "books",
            "controller" => "stories",
            "action" => "view",
            "id" => $this->page->page_story_id,
            "idpage" => $this->page->page_prev_page_id,
        ),null,true) ?>"><?php echo $this->translate('Back!') ?></a>
    <hr/>
    <?php } ?>
    <div id="pageVotes"></div>
        <script type="text/javascript">
            //Engine_Api_Votes.getVotes('pageVotes','<?php echo $this->baseUrl() ?>','<?php echo $this->page->page_id ?>');
//            document.title = "<?php echo str_replace('"', "'", $this->page->page_title) ?> | StoryCrossing";
//            if (window.innerWidth < 1390) {
//                dojo.byId('sidebarContainer').setAttribute('style','display:none;');
//            }
        </script>
    </div><!-- EOF SIDEBARContainer -->
    </div><!-- EOF SIDEBAR -->
</div><!-- EOP  -->
<?php endif; ?>
